# Compose used for production

version: '3.5'

services:
  rmod:
    build:
      context: ${SCRAPPER_PATH:-.}
      dockerfile: ./Dockerfile
      cache_from:
        - agoradigital/r-scrapper
    image: agoradigital/r-scrapper
    container_name: rmod
    volumes:
      - leggo_data:/agora-digital/leggo_data

volumes:
  leggo_data:
      name: leggo_data
