# Compose used for production

version: '3.5'

services:
  rmod:
    build:
      context: ${SCRAPPER_PATH:-.}
      dockerfile: ./Dockerfile
      cache_from:
        - ${PKG_IMAGE_TAG:-agoradigital/r-scrapper}
    image: ${PKG_IMAGE_TAG:-agoradigital/r-scrapper}
    container_name: rmod
    volumes:
      - leggo_data:/agora-digital/leggo_data

volumes:
  leggo_data:
      name: leggo_data
